In [67]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df=pd.read_csv(r"/Users/suriya/Ukesh_AIML_Projects/Content_Monetization_Modeler/Data/youtube_ad_revenue_dataset.csv")
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [68]:
df.duplicated().sum()

np.int64(2400)

In [69]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [70]:
df['likes']=df['likes'].fillna(df['likes'].mean())
df['comments']=df['comments'].fillna(df['comments'].mean())
df['watch_time_minutes']=df['watch_time_minutes'].fillna(df['watch_time_minutes'].mean())

In [71]:
df.isna().sum()

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

In [72]:
df['date']=pd.to_datetime(df['date'])
df['Year']=df['date'].dt.year
df['Month']=df['date'].dt.month
df['Day']=df['date'].dt.day
df['Hour']=df['date'].dt.hour
df['Minute']=df['date'].dt.minute
df['Seconds']=df['date'].dt.second
df['engagement_rate']=(df['likes']+df['comments'])/df['views']
df['likes_ratio']=df['likes']/df['views']
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,Year,Month,Day,Hour,Minute,Seconds,engagement_rate,likes_ratio
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.000000,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,2024,9,24,10,50,40,0.155093,0.122886
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.000000,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,2024,9,22,10,50,40,0.098632,0.064091
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.000000,57332.658498,26.200634,240534,Education,TV,CA,360.134008,2024,11,21,10,50,40,0.214519,0.195999
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.000000,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,2025,1,28,10,50,40,0.142814,0.118696
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.000000,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,2025,4,28,10,50,40,0.236121,0.187886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.000000,42075.704885,25.490195,210818,Education,Tablet,US,280.986396,2024,12,14,10,50,40,0.184715,0.169796
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.000000,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981,2024,7,13,10,50,40,0.174961,0.168740
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,274.349842,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106,2024,6,10,10,50,40,0.094901,0.068180
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.000000,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811,2024,12,22,10,50,40,0.168164,0.157812
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,274.349842,38466.837135,27.305703,517587,Tech,TV,CA,253.842824,2024,6,25,10,50,40,0.105161,0.077535

In [73]:
df=pd.get_dummies(df,columns=['category','device','country'],dtype='int')
scaler=StandardScaler()
df['views']=scaler.fit_transform(df[['views']])
df['likes']=scaler.fit_transform(df[['likes']])
df['watch_time_minutes']=scaler.fit_transform(df[['watch_time_minutes']])
df['video_length_minutes']=scaler.fit_transform(df[['video_length_minutes']])
df['subscribers']=scaler.fit_transform(df[['subscribers']])
df['engagement_rate']=scaler.fit_transform(df[['engagement_rate']])
df['likes_ratio']=scaler.fit_transform(df[['likes_ratio']])
df

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd,Year,...,device_Desktop,device_Mobile,device_TV,device_Tablet,country_AU,country_CA,country_DE,country_IN,country_UK,country_US
0,vid_3092,2024-09-24 10:50:40.993199,-0.638847,0.239775,320.000000,-0.872393,-1.627204,-0.950903,203.178237,2024,...,0,0,1,0,0,0,0,1,0,0
1,vid_3459,2024-09-22 10:50:40.993199,0.171818,-0.903658,346.000000,-1.764055,0.954887,0.810515,140.880508,2024,...,0,0,0,1,0,1,0,0,0,0
2,vid_4784,2024-11-21 10:50:40.993199,0.972474,1.736705,187.000000,1.563477,1.259475,-0.907735,360.134008,2024,...,0,0,1,0,0,1,0,0,0,0
3,vid_4078,2025-01-28 10:50:40.993199,0.341957,0.180530,242.000000,-0.490266,-0.525371,-0.235154,224.638261,2025,...,0,1,0,0,0,0,0,0,1,0
4,vid_3522,2025-04-28 10:50:40.993199,-1.109233,1.497749,477.000000,-1.728039,-1.160443,-1.596116,165.514388,2025,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,-1.469529,1.132404,147.000000,0.358242,1.171603,-1.010786,280.986396,2024,...,0,0,0,1,0,0,0,0,0,1
122396,vid_3890,2024-07-13 10:50:40.993199,1.282729,1.203498,63.000000,1.581729,0.026126,1.305878,354.612981,2024,...,1,0,0,0,0,0,0,0,1,0
122397,vid_3934,2024-06-10 10:50:40.993199,2.673870,-0.789117,274.349842,-0.789250,0.965313,0.258229,203.643106,2024,...,0,0,0,1,0,1,0,0,0,0
122398,vid_4260,2024-12-22 10:50:40.993199,2.403648,1.019838,106.000000,1.534622,-1.022254,0.287297,351.525811,2024,...,0,1,0,0,0,0,0,0,1,0
122399,vid_1056,2024-06-25 10:50:40.993199,-0.688888,-0.650878,274.349842,0.073157,1.396158,0.053041,253.842824,2024,...,0,0,1,0,0,1,0,0,0,0

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120000 entries, 0 to 122399
Data columns (total 33 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                120000 non-null  object
 1   date                    120000 non-null  datetime64[ns]
 2   views                   120000 non-null  float64
 3   likes                   120000 non-null  float64
 4   comments                120000 non-null  float64
 5   watch_time_minutes      120000 non-null  float64
 6   video_length_minutes    120000 non-null  float64
 7   subscribers             120000 non-null  float64
 8   ad_revenue_usd          120000 non-null  float64
 9   Year                    120000 non-null  int32
 10  Month                   120000 non-null  int32
 11  Day                     120000 non-null  int32
 12  Hour                    120000 non-null  int32
 13  Minute                  120000 non-null  int32
 14  Seconds                 120000 non-null  int32
 15  engagement_rate         120000 non-null  float64
 16  likes_ratio             120000 non-null  float64
 17  category_Education      120000 non-null  int64
 18  category_Entertainment  120000 non-null  int64
 19  category_Gaming         120000 non-null  int64
 20  category_Lifestyle      120000 non-null  int64
 21  category_Music          120000 non-null  int64
 22  category_Tech           120000 non-null  int64
 23  device_Desktop          120000 non-null  int64
 24  device_Mobile           120000 non-null  int64
 25  device_TV               120000 non-null  int64
 26  device_Tablet           120000 non-null  int64
 27  country_AU              120000 non-null  int64
 28  country_CA              120000 non-null  int64
 29  country_DE              120000 non-null  int64
 30  country_IN              120000 non-null  int64
 31  country_UK              120000 non-null  int64
 32  country_US              120000 non-null  int64
dtypes: datetime64[ns](1), float64(9), int32(6), int64(16), object(1)
memory usage: 28.4+ MB